tree 7035fdeed532c669206e0140cb85178b1c8360ea parent 66ef8bc0c03d35c30e43adde2b5726735c971b31 author Sascha Grunert <mail@saschagrunert.de> 1613487433 +0100 committer Kubernetes Prow Robot <k8s-ci-robot@users.noreply.github.com> 1613493537 -0800
Fix post-security-profiles-operator-push-image job

The job fails because of the error message:

```
error: while setting up the build environment: \
    unable to load seccomp BPF program: Invalid argument
```

See: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-security-profiles-operator-push-image/1361650313655750656

Setting the option `filter-syscalls = false` in `nix.conf` seems to
solve the issue.

Signed-off-by: Sascha Grunert <mail@saschagrunert.de>