Fix post-security-profiles-operator-push-image job
The job fails because of the error message:

```
error: while setting up the build environment: \
    unable to load seccomp BPF program: Invalid argument
```

See: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-security-profiles-operator-push-image/1361650313655750656

Setting the option `filter-syscalls = false` in `nix.conf` seems to
solve the issue.

Signed-off-by: Sascha Grunert <mail@saschagrunert.de>